import { coordinate, distanceKm, inBounds, deduplicate } from '../../shared/geo.js';

// Catálogo curado de webcams públicas com embeds oficiais e links autorizados de transmissão
// Cumpre as regras de: não quebrar paywalls, manter branding e attribution intactos, usar embeds e players oficiais
export const publicCamsCatalog = [
  {
    id: 'pub-tokyo-shibuya',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Shibuya Crossing Live',
    description: 'Cruzamento de pedestres mais movimentado do mundo em tempo real',
    country: 'Japão',
    countryCode: 'JP',
    state: 'Tóquio',
    city: 'Tóquio',
    latitude: 35.6595,
    longitude: 139.7004,
    category: 'Cidade · Trânsito',
    thumbnail: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dPYDe8e8p-4?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.youtube.com/watch?v=dPYDe8e8p-4',
    attribution: 'Shibuya Community Live Stream',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-nyc-times-square',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Times Square Live Cam',
    description: 'O coração de Manhattan em transmissão pública ao vivo',
    country: 'Estados Unidos',
    countryCode: 'US',
    state: 'Nova York',
    city: 'Nova York',
    latitude: 40.7580,
    longitude: -73.9855,
    category: 'Cidade · Turismo',
    thumbnail: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/1-iS7_Exw08?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.youtube.com/watch?v=1-iS7_Exw08',
    attribution: 'EarthCam Public Broadcast',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-paris-eiffel',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Torre Eiffel & Skyline de Paris',
    description: 'Vista panorâmica da Torre Eiffel sobre o Rio Sena',
    country: 'França',
    countryCode: 'FR',
    state: 'Île-de-France',
    city: 'Paris',
    latitude: 48.8584,
    longitude: 2.2945,
    category: 'Monumento · Turismo',
    thumbnail: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/JdqL89ZZwFw?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.youtube.com/watch?v=JdqL89ZZwFw',
    attribution: 'Média Paris Tourisme',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-rio-copacabana',
    provider: 'Câmeras do Mundo',
    providerId: 'camerasdomundo',
    name: 'Praia de Copacabana',
    description: 'Orla de Copacabana e calçadão em transmissão pública',
    country: 'Brasil',
    countryCode: 'BR',
    state: 'Rio de Janeiro',
    city: 'Rio de Janeiro',
    latitude: -22.9698,
    longitude: -43.1868,
    category: 'Praia · Natureza',
    thumbnail: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/rP1A_09YqGk?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://camerasdomundo.com/cameras/brasil/rio-de-janeiro/copacabana',
    attribution: 'Câmeras do Mundo / VejoAoVivo',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-london-abbey-road',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Abbey Road Crossing',
    description: 'A famosa travessia dos Beatles nos estúdios de Abbey Road',
    country: 'Reino Unido',
    countryCode: 'GB',
    state: 'Inglaterra',
    city: 'Londres',
    latitude: 51.5320,
    longitude: -0.1778,
    category: 'Cultura · Rua',
    thumbnail: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/wP23h2P2Fdg?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.abbeyroad.com/crossing',
    attribution: 'Abbey Road Studios Live Cam',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-lisbon-tejo',
    provider: 'Câmeras do Mundo',
    providerId: 'camerasdomundo',
    name: 'Praça do Comércio & Rio Tejo',
    description: 'Vista deslumbrante da histórica Praça do Comércio em Lisboa',
    country: 'Portugal',
    countryCode: 'PT',
    state: 'Lisboa',
    city: 'Lisboa',
    latitude: 38.7075,
    longitude: -9.1364,
    category: 'Cidade · Histórico',
    thumbnail: 'https://images.unsplash.com/photo-1508672019048-805b876b67e2?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/5_XqJz3_Lrk?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://camerasdomundo.com/cameras/portugal/lisboa/praca-do-comercio',
    attribution: 'Câmeras do Mundo / Turismo de Portugal',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-sp-paulista',
    provider: 'Câmeras do Mundo',
    providerId: 'camerasdomundo',
    name: 'Avenida Paulista',
    description: 'O coração pulsante de São Paulo e o centro financeiro da América Latina',
    country: 'Brasil',
    countryCode: 'BR',
    state: 'São Paulo',
    city: 'São Paulo',
    latitude: -23.5615,
    longitude: -46.6559,
    category: 'Cidade · Trânsito',
    thumbnail: 'https://images.unsplash.com/photo-1543059080-f9b1272213d5?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/cM3H5Lg268k?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://camerasdomundo.com/cameras/brasil/sao-paulo/avenida-paulista',
    attribution: 'Câmeras do Mundo / ClimaAoVivo SP',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-seoul-gangnam',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Gangnam & Teheran-ro',
    description: 'Avenida futurista de Gangnam iluminada pelos letreiros de Seul',
    country: 'Coreia do Sul',
    countryCode: 'KR',
    state: 'Seul',
    city: 'Seul',
    latitude: 37.4979,
    longitude: 127.0276,
    category: 'Cidade · Noturna',
    thumbnail: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/Q0A6B-i0Tkg?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.youtube.com/watch?v=Q0A6B-i0Tkg',
    attribution: 'Seoul Metropolitan Live Cam',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-rome-colosseum',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Coliseu de Roma',
    description: 'O monumento imperial romano transmitido ao vivo com turistas e praça',
    country: 'Itália',
    countryCode: 'IT',
    state: 'Lácio',
    city: 'Roma',
    latitude: 41.8902,
    longitude: 12.4922,
    category: 'Histórico · Monumento',
    thumbnail: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/f4d7hQvL01g?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/colosseo.html',
    attribution: 'Roma Capitale & Skyline Public Live',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-amsterdam-dam',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Dam Square & Palácio Real',
    description: 'A praça central de Amsterdã com bondes e pedestres',
    country: 'Países Baixos',
    countryCode: 'NL',
    state: 'Holanda do Norte',
    city: 'Amsterdã',
    latitude: 52.3731,
    longitude: 4.8926,
    category: 'Cidade · Centro Histórico',
    thumbnail: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/YpX3N6o-KjQ?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.youtube.com/watch?v=YpX3N6o-KjQ',
    attribution: 'Amsterdam City Live Streams',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-sydney-harbour',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Sydney Harbour & Opera House',
    description: 'Baía de Sydney com visão completa da Ópera e da Harbour Bridge',
    country: 'Austrália',
    countryCode: 'AU',
    state: 'Nova Gales do Sul',
    city: 'Sydney',
    latitude: -33.8568,
    longitude: 151.2153,
    category: 'Porto · Monumento',
    thumbnail: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/5eZ3g_f4bQE?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.sydneyoperahouse.com/',
    attribution: 'Port Authority of NSW Live View',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-barcelona-barceloneta',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Praia da Barceloneta',
    description: 'Calçadão e praia mediterrânea de Barcelona',
    country: 'Espanha',
    countryCode: 'ES',
    state: 'Catalunha',
    city: 'Barcelona',
    latitude: 41.3809,
    longitude: 2.1909,
    category: 'Praia · Lazer',
    thumbnail: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/D0y35bSjZkE?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.skylinewebcams.com/es/webcam/espana/cataluna/barcelona/playa-barceloneta.html',
    attribution: 'Ajuntament de Barcelona Webcams',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-reykjavik-harbor',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Porto Velho de Reykjavík & Harpa',
    description: 'Vista do porto islandês e montanha Esja ao fundo',
    country: 'Islândia',
    countryCode: 'IS',
    state: 'Capital Region',
    city: 'Reykjavík',
    latitude: 64.1504,
    longitude: -21.9333,
    category: 'Porto · Natureza',
    thumbnail: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/3E1z8-iVl2Y?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.livefromiceland.is/',
    attribution: 'Live from Iceland Public Webcams',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-bangkok-chao-phraya',
    provider: 'Public Live Streams',
    providerId: 'public',
    name: 'Rio Chao Phraya & Wat Arun',
    description: 'Tráfego fluvial de barcos tradicionais e o templo Wat Arun',
    country: 'Tailândia',
    countryCode: 'TH',
    state: 'Bangkok',
    city: 'Bangkok',
    latitude: 13.7437,
    longitude: 100.4889,
    category: 'Rio · Monumento',
    thumbnail: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/BvH_1G2_GZg?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://www.youtube.com/watch?v=BvH_1G2_GZg',
    attribution: 'Bangkok Tourism Authority Stream',
    isLive: true,
    status: 'LIVE'
  },
  {
    id: 'pub-salvador-barra',
    provider: 'Câmeras do Mundo',
    providerId: 'camerasdomundo',
    name: 'Farol da Barra & Praia do Farol',
    description: 'Vista histórica da entrada da Baía de Todos os Santos',
    country: 'Brasil',
    countryCode: 'BR',
    state: 'Bahia',
    city: 'Salvador',
    latitude: -13.0104,
    longitude: -38.5323,
    category: 'Praia · Histórico',
    thumbnail: 'https://images.unsplash.com/photo-1582234033282-598d1a123f1c?w=640&auto=format&fit=crop&q=80',
    streamType: 'youtube',
    streamUrl: '',
    embedUrl: 'https://www.youtube-nocookie.com/embed/rP1A_09YqGk?autoplay=1&mute=1&playsinline=1',
    sourceUrl: 'https://camerasdomundo.com/cameras/brasil/bahia/salvador-farol-da-barra',
    attribution: 'Câmeras do Mundo / VejoAoVivo',
    isLive: true,
    status: 'LIVE'
  }
];

export const publicWebcamsProvider = {
  id: 'public',
  name: 'Câmeras Públicas & Turismo',
  configured: () => true,

  async search({ lat, lon, radius = 150, country, category }) {
    let list = [...publicCamsCatalog];
    if (country) {
      list = list.filter(item => item.countryCode === country.toUpperCase());
    }
    if (category) {
      const catLower = category.toLowerCase();
      list = list.filter(item => item.category.toLowerCase().includes(catLower));
    }
    if (Number.isFinite(lat) && Number.isFinite(lon)) {
      list = list.filter(item => distanceKm(lat, lon, item.latitude, item.longitude) <= radius)
                 .sort((a, b) => distanceKm(lat, lon, a.latitude, a.longitude) - distanceKm(lat, lon, b.latitude, b.longitude));
    }
    return list;
  },

  async viewport(box) {
    return publicCamsCatalog.filter(item => inBounds(item, box));
  },

  async detail(id) {
    const cam = publicCamsCatalog.find(item => item.id === id);
    if (!cam) throw new Error('Câmera não encontrada no catálogo público.');
    return cam;
  }
};
